"""Active-seed mode — in-process libtorrent session.

Per Constitution Article IX + spec FR-023. Grabarr runs as the sole peer
for every torrent it generates; a BitTorrent client (Deluge,
qBittorrent, Transmission, rTorrent) connects to the internal tracker
and pulls pieces from this session.

Session invariants:
  - DHT, LSD disabled.
  - PEX allowed but restricted to the internal peer set.
  - Listen ports in [45000, 45100] (configurable).
  - ``add_torrent`` flags set SEED_MODE so libtorrent treats an
    already-hashed file as "fully downloaded" without re-verifying.
  - State persisted to ``{data_dir}/session.state`` on shutdown and
    restored on startup (spec FR-023 final clause).
"""

from __future__ import annotations

import datetime as dt
import hashlib
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING

from grabarr.core.logging import setup_logger

if TYPE_CHECKING:
    import libtorrent  # type: ignore[import-not-found]

_log = setup_logger(__name__)


@dataclass(frozen=True)
class ActiveSeedBlob:
    """Result of generating an active-seed torrent."""

    bencoded: bytes
    info_hash: str
    piece_count: int
    piece_size: int


def _pick_piece_size(file_size: int) -> int:
    """Same ladder as the webseed builder (research R-3)."""
    if file_size < 50 * 1024 * 1024:
        return 256 * 1024
    if file_size < 1024 * 1024 * 1024:
        return 1 * 1024 * 1024
    return 4 * 1024 * 1024


class ActiveSeedServer:
    """Singleton libtorrent session + torrent registration.

    Use :func:`get_active_seed_server` to obtain the process-wide
    instance. The server is started lazily on first access and
    persisted on FastAPI shutdown via a lifespan hook.
    """

    _instance: "ActiveSeedServer | None" = None

    def __init__(
        self,
        *,
        data_dir: Path,
        listen_port_min: int = 45000,
        listen_port_max: int = 45100,
    ) -> None:
        import libtorrent as lt

        self._lt = lt
        self._data_dir = data_dir
        self._state_path = data_dir / "session.state"
        self._listen_range = (listen_port_min, listen_port_max)

        settings = lt.default_settings()
        settings.update(
            {
                "listen_interfaces": (
                    f"0.0.0.0:{listen_port_min}-{listen_port_max},"
                    f"[::]:{listen_port_min}-{listen_port_max}"
                ),
                "enable_dht": False,
                "enable_lsd": False,
                "enable_upnp": False,
                "enable_natpmp": False,
                "anonymous_mode": False,
                # Tame outbound connection bursts so we don't hammer
                # peers we don't have.
                "max_out_request_queue": 64,
                "seed_choking_algorithm": 1,  # round-robin
            }
        )
        self._session = lt.session(settings)

        if self._state_path.exists():
            try:
                blob = self._state_path.read_bytes()
                self._session.load_state(lt.bdecode(blob))
                _log.info("libtorrent session state restored from %s", self._state_path)
            except Exception as exc:  # noqa: BLE001
                _log.warning("failed to restore libtorrent session state: %s", exc)

        self._active_torrents: dict[str, "libtorrent.torrent_handle"] = {}

    # ---- lifecycle -----------------------------------------------------

    def shutdown(self) -> None:
        """Save state to disk and pause the session. Idempotent."""
        try:
            blob = self._lt.bencode(self._session.save_state())
            self._data_dir.mkdir(parents=True, exist_ok=True)
            self._state_path.write_bytes(blob)
            _log.info("libtorrent session state saved to %s", self._state_path)
        except Exception as exc:  # noqa: BLE001
            _log.warning("failed to save libtorrent session state: %s", exc)
        # Pause the session so torrents stop announcing during shutdown.
        try:
            self._session.pause()
        except Exception:  # noqa: BLE001
            pass

    # ---- torrent registration -----------------------------------------

    def create_and_seed(
        self,
        *,
        file_path: Path,
        announce_url: str,
        display_name: str | None = None,
        comment: str = "Generated by Grabarr",
    ) -> ActiveSeedBlob:
        """Build a .torrent from ``file_path`` and add it to the session.

        Returns the bencoded .torrent blob + metadata.
        """
        lt = self._lt
        file_size = file_path.stat().st_size
        if file_size <= 0:
            raise ValueError(f"active_seed needs a non-empty file: {file_path}")

        piece_size = _pick_piece_size(file_size)
        # The name inside the torrent MUST match the real filename on
        # disk so libtorrent's ``set_piece_hashes`` can locate it.
        # ``display_name`` only influences what the *arr client shows
        # to the user — pass it as ``comment`` or ignore here.
        name = file_path.name
        _ = display_name  # reserved for future per-client title rewriting

        fs = lt.file_storage()
        fs.add_file(name, file_size)
        creator = lt.create_torrent(fs, piece_size)
        creator.add_tracker(announce_url)
        creator.set_creator(f"Grabarr/{_grabarr_version()}")
        creator.set_comment(comment)

        # Hash the file pieces. libtorrent's ``set_piece_hashes`` runs
        # this synchronously; for large files we could async this, but
        # sync is fine for the current sync-download flow.
        lt.set_piece_hashes(creator, str(file_path.parent))

        # Emit the bencoded .torrent.
        torrent_dict = creator.generate()
        bencoded = lt.bencode(torrent_dict)
        info_hash = hashlib.sha1(  # noqa: S324
            lt.bencode(torrent_dict[b"info"]),
            usedforsecurity=False,
        ).hexdigest()

        # Add to the session in SEED_MODE so libtorrent trusts the file.
        ti = lt.torrent_info(torrent_dict)
        params = lt.add_torrent_params()
        params.ti = ti
        params.save_path = str(file_path.parent)
        params.flags = lt.torrent_flags.seed_mode
        handle = self._session.add_torrent(params)
        self._active_torrents[info_hash] = handle
        _log.info(
            "active_seed torrent added: info_hash=%s piece_count=%d piece_size=%d",
            info_hash,
            creator.num_pieces(),
            piece_size,
        )

        return ActiveSeedBlob(
            bencoded=bencoded,
            info_hash=info_hash,
            piece_count=creator.num_pieces(),
            piece_size=piece_size,
        )

    def remove(self, info_hash: str) -> None:
        """Remove a torrent from the session (called by the cleanup sweeper)."""
        handle = self._active_torrents.pop(info_hash, None)
        if handle is None:
            return
        try:
            self._session.remove_torrent(handle)
        except Exception as exc:  # noqa: BLE001
            _log.warning("failed to remove torrent %s: %s", info_hash, exc)

    # ---- stats ---------------------------------------------------------

    def active_count(self) -> int:
        return len(self._active_torrents)


_server: ActiveSeedServer | None = None


def get_active_seed_server(data_dir: Path | None = None) -> ActiveSeedServer:
    """Return the process-wide :class:`ActiveSeedServer`, creating it on first call."""
    global _server
    if _server is None:
        if data_dir is None:
            from grabarr.core.config import get_settings

            data_dir = Path(get_settings().server.data_dir)
        import os

        pmin = int(os.environ.get("GRABARR_TORRENT_LISTEN_PORT_MIN", "45000"))
        pmax = int(os.environ.get("GRABARR_TORRENT_LISTEN_PORT_MAX", "45100"))
        _server = ActiveSeedServer(
            data_dir=data_dir,
            listen_port_min=pmin,
            listen_port_max=pmax,
        )
    return _server


def shutdown_active_seed_server() -> None:
    """Idempotent shutdown; called from the FastAPI lifespan."""
    global _server
    if _server is not None:
        _server.shutdown()
        _server = None


def _grabarr_version() -> str:
    from grabarr import __version__

    return __version__
