"""Webseed (BEP-19) torrent generator — pure Python, no libtorrent.

For v1.0 MVP, webseed is the shipping torrent mode (active_seed with a
libtorrent session is deferred until Docker deployment). BitTorrent
clients that support BEP-19 (all modern Deluge/qBittorrent/Transmission/
rTorrent releases) will fetch pieces directly from the webseed URL
over HTTP with Range requests.

The `.torrent` file still needs a tracker announce URL for clients that
require one; we point at Grabarr's own /announce stub which always
returns an empty peer list.
"""

from __future__ import annotations

import datetime as dt
import hashlib
from dataclasses import dataclass
from pathlib import Path

from grabarr.torrents.bencode import encode

# Piece-size ladder matching research R-3: balance number of pieces vs
# first-piece latency. For webseed, all pieces are hashed up front since
# the file must exist before we can emit the torrent.
_PIECE_SIZES: list[tuple[int, int]] = [
    (50 * 1024 * 1024, 256 * 1024),          # < 50 MiB  → 256 KiB pieces
    (1 * 1024 * 1024 * 1024, 1 * 1024 * 1024),  # < 1 GiB → 1 MiB pieces
    (float("inf"), 4 * 1024 * 1024),         # >= 1 GiB → 4 MiB pieces
]


def _pick_piece_size(file_size: int) -> int:
    for threshold, size in _PIECE_SIZES:
        if file_size < threshold:
            return size
    return _PIECE_SIZES[-1][1]


@dataclass(frozen=True)
class TorrentBlob:
    """Result of generating a .torrent file."""

    bencoded: bytes      # the .torrent bytes to serve
    info_hash: str       # 40-char hex SHA-1 of the bencoded ``info`` dict
    piece_count: int
    piece_size: int


def build_webseed_torrent(
    *,
    file_path: Path,
    announce_url: str,
    webseed_url: str,
    display_name: str | None = None,
    comment: str = "Generated by Grabarr",
) -> TorrentBlob:
    """Build a BEP-3 + BEP-19 .torrent for a single file.

    Parameters
    ----------
    file_path:
        Local path to the content file. Must exist.
    announce_url:
        Tracker URL written into the ``announce`` key. Grabarr's
        internal stub tracker at ``http://{host}:{tracker_port}/announce``
        is the typical value.
    webseed_url:
        Fully-qualified URL that serves the file over HTTP with
        ``Range`` support. Written to the ``url-list`` key per BEP-19.
    display_name:
        ``info.name`` value. Defaults to ``file_path.name``.
    comment:
        Human-readable comment. Appears in some clients' UI.
    """
    file_size = file_path.stat().st_size
    if file_size <= 0:
        raise ValueError(f"webseed torrent needs a non-empty file: {file_path}")

    piece_size = _pick_piece_size(file_size)
    pieces: list[bytes] = []
    with file_path.open("rb") as fh:
        while chunk := fh.read(piece_size):
            pieces.append(hashlib.sha1(chunk, usedforsecurity=False).digest())

    name = display_name or file_path.name

    info: dict = {
        "name": name,
        "length": file_size,
        "piece length": piece_size,
        "pieces": b"".join(pieces),
    }

    # SHA-1 of the bencoded info dict is the torrent's info_hash.
    info_bencoded = encode(info)
    info_hash = hashlib.sha1(info_bencoded, usedforsecurity=False).hexdigest()

    torrent: dict = {
        "announce": announce_url,
        "info": info,
        "creation date": int(dt.datetime.now(dt.UTC).timestamp()),
        "created by": "Grabarr/1.0.0",
        "comment": comment,
        "url-list": [webseed_url],  # BEP-19
    }
    return TorrentBlob(
        bencoded=encode(torrent),
        info_hash=info_hash,
        piece_count=len(pieces),
        piece_size=piece_size,
    )
