#!/usr/bin/env bash
# Start Grabarr. Stops any stale instance first, then launches uvicorn
# in the background, waits for /healthz to respond, and writes the PID
# to .grabarr.pid so stop.sh can find it.
#
# Usage:
#   ./start.sh                     # start in background, return when ready
#   ./start.sh --foreground        # run in the foreground (Ctrl-C to stop)
#   HOST=127.0.0.1 ./start.sh      # bind local-only
#   RELOAD=0 ./start.sh            # disable hot reload
#   FLARESOLVERR_URL=... ./start.sh # wire an external FlareSolverr

set -e

FG=0
for arg in "$@"; do
    case "$arg" in
        --foreground|-f) FG=1 ;;
    esac
done

HOST="${HOST:-0.0.0.0}"
PORT="${PORT:-8080}"
RELOAD="${RELOAD:-1}"
PIDFILE=".grabarr.pid"
LOGFILE="${LOGFILE:-data/grabarr-server.log}"

say() { printf '[grabarr] %s\n' "$1"; }

# 1. Ensure we're in the repo root and the runtime dirs exist
cd "$(dirname "$0")"
mkdir -p data downloads/incoming downloads/ready data/shelfmark

# 2. Redirect Shelfmark's hardcoded /var/log /config /books /tmp/shelfmark
#    into our project-local data dir so we don't need root.
export LOG_ROOT="$(pwd)/data/shelfmark/log_root"
export CONFIG_DIR="$(pwd)/data/shelfmark/config"
export TMP_DIR="$(pwd)/data/shelfmark/tmp"
export INGEST_DIR="$(pwd)/data/shelfmark/ingest"
mkdir -p "$LOG_ROOT/shelfmark" "$CONFIG_DIR" "$TMP_DIR" "$INGEST_DIR"

# 3. FlareSolverr convenience: FLARESOLVERR_URL=host:port → Shelfmark env vars.
if [ -n "${FLARESOLVERR_URL:-}" ]; then
    v="${FLARESOLVERR_URL%/v1}"
    v="${v%/}"
    export GRABARR_SHELFMARK_EXT_BYPASSER_URL="$v"
    export GRABARR_SHELFMARK_EXT_BYPASSER_PATH="/v1"
    say "FlareSolverr endpoint: $v/v1"
fi

# 4. First-run config.yaml (kept compatible with the old run.sh).
if [ ! -f config.yaml ]; then
    cat > config.yaml <<EOF
# Auto-generated by start.sh for local terminal launch.
# Edit this file for source credentials. config.example.yaml is the full reference.

logging:
  level: INFO
  format: text

server:
  host: 0.0.0.0
  port: 8080
  data_dir: ./data
  downloads_dir: ./downloads

sources:
  anna_archive:
    member_key: ""
  zlibrary:
    remix_userid: ""
    remix_userkey: ""

master_secret: ""

initial_settings:
  "download.mode": "sync"
  "download.hybrid_threshold_mb": 50
  "torrent.mode": "active_seed"
  "torrent.seed_retention_hours": 24
  "bypass.mode": "external"
  "bypass.flaresolverr_url": "http://flaresolverr:8191"
  "notifications.flap_cooldown_minutes": 10
  "metadata.ia_contact_email": ""
EOF
    say "created dev config.yaml"
fi

# 5. Always stop any stale instance before starting a new one.
./stop.sh >/dev/null 2>&1 || true

# 6. Build uvicorn argv.
RELOAD_ARGS=()
if [ "$RELOAD" = "1" ] || [ "$RELOAD" = "true" ]; then
    RELOAD_ARGS=(
        --reload
        --reload-dir grabarr
        --reload-include '*.py'
        --reload-include '*.html'
        --reload-include '*.css'
    )
fi

LAN_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo 127.0.0.1)
say "starting on http://$HOST:$PORT"
if [ "$HOST" = "0.0.0.0" ]; then
    say "LAN: http://$LAN_IP:$PORT   (Prowlarr: http://$LAN_IP:$PORT/torznab/<slug>/api)"
fi
[ "$RELOAD" = "1" ] && say "hot-reload ON (RELOAD=0 to disable)"

# 7. Launch.
if [ "$FG" = "1" ]; then
    exec uv run uvicorn grabarr.api.app:app --host "$HOST" --port "$PORT" "${RELOAD_ARGS[@]}"
fi

# Background mode: redirect to log file + record PID.
nohup uv run uvicorn grabarr.api.app:app \
    --host "$HOST" --port "$PORT" "${RELOAD_ARGS[@]}" \
    > "$LOGFILE" 2>&1 &

pid=$!
echo "$pid" > "$PIDFILE"
disown "$pid" 2>/dev/null || true

# 8. Wait up to 30 s for /healthz to come up.
for i in $(seq 1 30); do
    if curl -sf -m 2 "http://127.0.0.1:$PORT/healthz" >/dev/null 2>&1; then
        say "ready (pid $pid) — logs: $LOGFILE"
        exit 0
    fi
    # Server may have died already.
    if ! kill -0 "$pid" 2>/dev/null; then
        say "failed to start — last log lines:"
        tail -20 "$LOGFILE"
        rm -f "$PIDFILE"
        exit 1
    fi
    sleep 1
done

say "did not become healthy within 30 s — last log lines:"
tail -20 "$LOGFILE"
exit 1
