"""initial schema

Revision ID: 770d9a85f327
Revises: 
Create Date: 2026-04-23 13:19:16.635227
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import grabarr.db.base  # noqa: F401  (UUIDColumn referenced in op.create_table calls below)


revision: str = '770d9a85f327'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adapter_health',
    sa.Column('adapter_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=True),
    sa.Column('last_check_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_recheck_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('healthy', 'degraded', 'unhealthy')", name='adapter_health_status_valid'),
    sa.PrimaryKeyConstraint('adapter_id')
    )
    op.create_table('apprise_urls',
    sa.Column('id', grabarr.db.base.UUIDColumn(length=36), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('url_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('subscribed_events', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bypass_sessions',
    sa.Column('domain', sa.String(length=256), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=False),
    sa.Column('cf_clearance', sa.Text(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mode_used', sa.String(length=16), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.CheckConstraint("mode_used IN ('external', 'internal')", name='bypass_sessions_mode_valid'),
    sa.PrimaryKeyConstraint('domain')
    )
    with op.batch_alter_table('bypass_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_bypass_sessions_expires_at', ['expires_at'], unique=False)

    op.create_table('notifications_log',
    sa.Column('id', grabarr.db.base.UUIDColumn(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('coalesced', sa.Boolean(), nullable=False),
    sa.Column('dispatch_status', sa.String(length=16), nullable=False),
    sa.CheckConstraint("dispatch_status IN ('sent', 'failed', 'suppressed')", name='notifications_log_dispatch_status_valid'),
    sa.CheckConstraint("severity IN ('info', 'warning', 'error')", name='notifications_log_severity_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications_log', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_log_dispatched_at', ['dispatched_at'], unique=False)
        batch_op.create_index('ix_notifications_log_event_source_ts', ['event_type', 'source_id', 'dispatched_at'], unique=False)

    op.create_table('profiles',
    sa.Column('id', grabarr.db.base.UUIDColumn(length=36), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('media_type', sa.String(length=32), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('newznab_categories', sa.JSON(), nullable=False),
    sa.Column('download_mode_override', sa.String(length=32), nullable=True),
    sa.Column('torrent_mode_override', sa.String(length=32), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('api_key_hash', sa.String(length=128), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("mode IN ('first_match', 'aggregate_all')", name='profiles_mode_valid'),
    sa.CheckConstraint("slug GLOB '[a-z0-9][a-z0-9_-]*'", name='profiles_slug_charset'),
    sa.CheckConstraint('length(slug) >= 2 AND length(slug) <= 64', name='profiles_slug_length'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index('ix_profiles_enabled_default', ['enabled', 'is_default'], unique=False)

    op.create_table('search_cache',
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('profile_id', grabarr.db.base.UUIDColumn(length=36), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('stored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('cache_key')
    )
    with op.batch_alter_table('search_cache', schema=None) as batch_op:
        batch_op.create_index('ix_search_cache_expires_at', ['expires_at'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tracker_peers',
    sa.Column('info_hash', sa.String(length=40), nullable=False),
    sa.Column('peer_id', sa.String(length=40), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uploaded', sa.BigInteger(), nullable=False),
    sa.Column('downloaded', sa.BigInteger(), nullable=False),
    sa.Column('left_bytes', sa.BigInteger(), nullable=False),
    sa.Column('event', sa.String(length=16), nullable=True),
    sa.CheckConstraint("event IS NULL OR event IN ('started','stopped','completed')", name='tracker_peers_event_valid'),
    sa.PrimaryKeyConstraint('info_hash', 'peer_id')
    )
    with op.batch_alter_table('tracker_peers', schema=None) as batch_op:
        batch_op.create_index('ix_tracker_peers_last_seen_at', ['last_seen_at'], unique=False)

    op.create_table('webhook_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('headers', sa.JSON(), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('subscribed_events', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.CheckConstraint('id = 1', name='webhook_config_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zlibrary_quota',
    sa.Column('date_utc', sa.Date(), nullable=False),
    sa.Column('downloads_used', sa.Integer(), nullable=False),
    sa.Column('downloads_max', sa.Integer(), nullable=False),
    sa.Column('reset_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('date_utc')
    )
    op.create_table('downloads',
    sa.Column('id', grabarr.db.base.UUIDColumn(length=36), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('profile_id', grabarr.db.base.UUIDColumn(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=False),
    sa.Column('media_type', sa.String(length=32), nullable=False),
    sa.Column('download_mode', sa.String(length=32), nullable=False),
    sa.Column('torrent_mode', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('magic_verified', sa.Boolean(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('info_hash', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seeded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('queued','resolving','downloading','verifying','ready','seeding','completed','failed')", name='downloads_status_valid'),
    sa.CheckConstraint('info_hash IS NULL OR length(info_hash) = 40', name='downloads_info_hash_length'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('downloads', schema=None) as batch_op:
        batch_op.create_index('ix_downloads_info_hash', ['info_hash'], unique=True)
        batch_op.create_index('ix_downloads_profile_status', ['profile_id', 'status'], unique=False)
        batch_op.create_index('ix_downloads_started_at_desc', ['started_at'], unique=False)

    op.create_table('torrents',
    sa.Column('info_hash', sa.String(length=40), nullable=False),
    sa.Column('download_id', grabarr.db.base.UUIDColumn(length=36), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('total_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('piece_size_bytes', sa.Integer(), nullable=False),
    sa.Column('piece_count', sa.Integer(), nullable=False),
    sa.Column('webseed_url', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_announced_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("mode IN ('active_seed', 'webseed')", name='torrents_mode_valid'),
    sa.CheckConstraint('length(info_hash) = 40', name='torrents_info_hash_length'),
    sa.ForeignKeyConstraint(['download_id'], ['downloads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('info_hash'),
    sa.UniqueConstraint('download_id')
    )
    with op.batch_alter_table('torrents', schema=None) as batch_op:
        batch_op.create_index('ix_torrents_expires_at', ['expires_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('torrents', schema=None) as batch_op:
        batch_op.drop_index('ix_torrents_expires_at')

    op.drop_table('torrents')
    with op.batch_alter_table('downloads', schema=None) as batch_op:
        batch_op.drop_index('ix_downloads_started_at_desc')
        batch_op.drop_index('ix_downloads_profile_status')
        batch_op.drop_index('ix_downloads_info_hash')

    op.drop_table('downloads')
    op.drop_table('zlibrary_quota')
    op.drop_table('webhook_config')
    with op.batch_alter_table('tracker_peers', schema=None) as batch_op:
        batch_op.drop_index('ix_tracker_peers_last_seen_at')

    op.drop_table('tracker_peers')
    op.drop_table('settings')
    with op.batch_alter_table('search_cache', schema=None) as batch_op:
        batch_op.drop_index('ix_search_cache_expires_at')

    op.drop_table('search_cache')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index('ix_profiles_enabled_default')

    op.drop_table('profiles')
    with op.batch_alter_table('notifications_log', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_log_event_source_ts')
        batch_op.drop_index('ix_notifications_log_dispatched_at')

    op.drop_table('notifications_log')
    with op.batch_alter_table('bypass_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_bypass_sessions_expires_at')

    op.drop_table('bypass_sessions')
    op.drop_table('apprise_urls')
    op.drop_table('adapter_health')
    # ### end Alembic commands ###
