#!/usr/bin/env bash
# Terminal launcher for Grabarr (no Docker).
#
# Defaults bind 0.0.0.0:8080 so the service is reachable from any host on
# your LAN. Override with HOST=127.0.0.1 or PORT=9090 as needed.
#
# Usage:
#   ./run.sh                          # dev default — hot-reload ON
#   RELOAD=0 ./run.sh                 # disable hot-reload
#   HOST=127.0.0.1 ./run.sh           # bind local only
#   GRABARR_TORRENT_MODE=webseed ./run.sh   # override any setting

set -e

HOST="${HOST:-0.0.0.0}"
PORT="${PORT:-8080}"
RELOAD="${RELOAD:-1}"

# CloudFlare bypasser — one knob instead of two. Accepts either a bare
# host:port (http://flaresolverr:8191) or a full /v1 URL. Set this via
# env var to avoid editing config files:
#
#   FLARESOLVERR_URL=http://192.168.1.50:8191 ./run.sh
#
if [ -n "${FLARESOLVERR_URL:-}" ]; then
    # Strip a trailing /v1 so we end up with host+port in EXT_BYPASSER_URL.
    FLARE_HOSTPORT="${FLARESOLVERR_URL%/v1}"
    FLARE_HOSTPORT="${FLARE_HOSTPORT%/}"
    export GRABARR_SHELFMARK_EXT_BYPASSER_URL="$FLARE_HOSTPORT"
    export GRABARR_SHELFMARK_EXT_BYPASSER_PATH="/v1"
    echo "[grabarr] FlareSolverr endpoint: $FLARE_HOSTPORT/v1"
fi

# Ensure the runtime dirs exist under the project root (not /data).
mkdir -p data downloads/incoming downloads/ready data/shelfmark

# Shelfmark's vendored env.py hardcodes /var/log/shelfmark. Redirect it
# to our project-local data dir so we don't need root. Same for the
# Shelfmark-side CONFIG_DIR / TMP_DIR / INGEST_DIR used by the internal
# bypasser + recording.
export LOG_ROOT="$(pwd)/data/shelfmark/log_root"
export CONFIG_DIR="$(pwd)/data/shelfmark/config"
export TMP_DIR="$(pwd)/data/shelfmark/tmp"
export INGEST_DIR="$(pwd)/data/shelfmark/ingest"
mkdir -p "$LOG_ROOT/shelfmark" "$CONFIG_DIR" "$TMP_DIR" "$INGEST_DIR"

# First-run: write a minimal dev-focused config.yaml (relative paths).
# config.example.yaml remains the reference for Docker deployments.
if [ ! -f config.yaml ]; then
    cat > config.yaml <<EOF
# Auto-generated by run.sh for local terminal launch.
# Edit this file for source credentials (AA member key, Z-Lib cookies, etc.)
# See config.example.yaml for the full reference.

logging:
  level: INFO
  format: text

server:
  host: 0.0.0.0
  port: 8080
  data_dir: ./data
  downloads_dir: ./downloads

sources:
  anna_archive:
    member_key: ""
  zlibrary:
    remix_userid: ""
    remix_userkey: ""

master_secret: ""

initial_settings:
  "download.mode": "sync"
  "download.hybrid_threshold_mb": 50
  "torrent.mode": "active_seed"
  "torrent.seed_retention_hours": 24
  "bypass.mode": "external"
  "bypass.flaresolverr_url": "http://flaresolverr:8191/v1"
  "notifications.flap_cooldown_minutes": 10
  "metadata.ia_contact_email": ""
EOF
    echo "[grabarr] created dev config.yaml (relative paths for local use)"
    echo "[grabarr]   edit it to set IA contact email + any source credentials"
fi

# Show the LAN address prominently.
LAN_IP=$(hostname -I | awk '{print $1}' 2>/dev/null || echo '127.0.0.1')
echo "[grabarr] starting on http://$HOST:$PORT"
if [ "$HOST" = "0.0.0.0" ]; then
    echo "[grabarr] reachable on LAN at: http://$LAN_IP:$PORT"
    echo "[grabarr]   Prowlarr indexer URL: http://$LAN_IP:$PORT/torznab/<profile_slug>/api"
fi
echo "[grabarr] Ctrl+C to stop. Data persisted under ./data/ and ./downloads/."

RELOAD_ARGS=()
if [ "$RELOAD" = "1" ] || [ "$RELOAD" = "true" ]; then
    # Watch Python source + Jinja templates; skip data/downloads/cache
    # dirs so writes there don't restart the server.
    RELOAD_ARGS=(
        --reload
        --reload-dir grabarr
        --reload-include "*.py"
        --reload-include "*.html"
        --reload-include "*.css"
    )
    echo "[grabarr] hot-reload ON (set RELOAD=0 to disable)"
else
    echo "[grabarr] hot-reload OFF"
fi
echo

exec uv run uvicorn grabarr.api.app:app \
    --host "$HOST" \
    --port "$PORT" \
    "${RELOAD_ARGS[@]}" \
    "$@"
