#!/usr/bin/env bash
# Terminal launcher for Grabarr (no Docker).
#
# Defaults bind 0.0.0.0:8080 so the service is reachable from any host on
# your LAN. Override with HOST=127.0.0.1 or PORT=9090 as needed.
#
# Usage:
#   ./run.sh                          # dev default, reload OFF
#   ./run.sh --reload                 # hot-reload on code changes
#   HOST=127.0.0.1 ./run.sh           # bind local only
#   GRABARR_TORRENT_MODE=webseed ./run.sh   # override any setting

set -e

HOST="${HOST:-0.0.0.0}"
PORT="${PORT:-8080}"

# Ensure the runtime dirs exist under the project root (not /data).
mkdir -p data downloads/incoming downloads/ready

# First-run: write a minimal dev-focused config.yaml (relative paths).
# config.example.yaml remains the reference for Docker deployments.
if [ ! -f config.yaml ]; then
    cat > config.yaml <<EOF
# Auto-generated by run.sh for local terminal launch.
# Edit this file for source credentials (AA member key, Z-Lib cookies, etc.)
# See config.example.yaml for the full reference.

logging:
  level: INFO
  format: text

server:
  host: 0.0.0.0
  port: 8080
  data_dir: ./data
  downloads_dir: ./downloads

sources:
  anna_archive:
    member_key: ""
  zlibrary:
    remix_userid: ""
    remix_userkey: ""

master_secret: ""

initial_settings:
  "download.mode": "sync"
  "download.hybrid_threshold_mb": 50
  "torrent.mode": "active_seed"
  "torrent.seed_retention_hours": 24
  "bypass.mode": "external"
  "bypass.flaresolverr_url": "http://flaresolverr:8191/v1"
  "notifications.flap_cooldown_minutes": 10
  "metadata.ia_contact_email": ""
EOF
    echo "[grabarr] created dev config.yaml (relative paths for local use)"
    echo "[grabarr]   edit it to set IA contact email + any source credentials"
fi

# Show the LAN address prominently.
LAN_IP=$(hostname -I | awk '{print $1}' 2>/dev/null || echo '127.0.0.1')
echo "[grabarr] starting on http://$HOST:$PORT"
if [ "$HOST" = "0.0.0.0" ]; then
    echo "[grabarr] reachable on LAN at: http://$LAN_IP:$PORT"
    echo "[grabarr]   Prowlarr indexer URL: http://$LAN_IP:$PORT/torznab/<profile_slug>/api"
fi
echo "[grabarr] Ctrl+C to stop. Data persisted under ./data/ and ./downloads/."
echo

exec uv run uvicorn grabarr.api.app:app \
    --host "$HOST" \
    --port "$PORT" \
    "$@"
