"""add profiles.api_key_plain

Revision ID: b8756945d4db
Revises: 770d9a85f327
Create Date: 2026-04-23 15:43:14.490921
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b8756945d4db'
down_revision: Union[str, None] = '770d9a85f327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key_plain', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('api_key_plain')

    # ### end Alembic commands ###
