"""Click-driving CDP bypass for adapters whose download URL is generated by JS.

Many modern WordPress-style ROM/scene sites hide the actual file URL
behind a click → AJAX → file URL flow:

  - User clicks "Download Now"
  - JS fires a fetch() against ``/wp-admin/admin-ajax.php`` (or similar)
    with a one-shot nonce, possibly waiting on a synthetic countdown.
  - Server responds with a signed temporary file URL.
  - JS sets ``window.location = url`` (or fabricates a hidden ``<a download>``
    and clicks it), triggering the browser's native download.

``bypass.service.fetch_html`` returns the post-CF HTML — but it cannot
follow the click handler. This module boots a real Chromium via the
vendored SeleniumBase ``cdp_driver``, navigates to the URL, clicks the
configured button, and **captures the URL the browser was about to
download** via the CDP ``Browser.downloadWillBegin`` event.

The captured URL plus the session cookies are returned to the caller,
which performs the actual file fetch with httpx as usual. The browser
is closed before the function returns; nothing persists.

The module is **adapter-agnostic** — any future scraper that hits the
same click-to-download wall can call it. The vendored Shelfmark code
is not modified; we reach into it via documented entry points only.

Usage::

    from grabarr.bypass.click_driver import click_and_capture
    capture = await asyncio.to_thread(
        click_and_capture,
        url="https://example.com/download/abc",
        button_text="Download Now",
        wait_for_url_pattern=r"\\.(zip|7z|rar|iso|nes)$",
        timeout=45,
    )
    info = DownloadInfo(
        download_url=capture.download_url,
        size_bytes=None,
        content_type=None,
        filename_hint=capture.suggested_filename,
        extra_headers={
            "User-Agent": capture.user_agent,
            "Cookie": "; ".join(f"{k}={v}" for k, v in capture.cookies.items()),
        },
    )
"""

from __future__ import annotations

import asyncio
import re
from dataclasses import dataclass
from typing import Any

from grabarr.core.logging import setup_logger

# AdapterBypassError is imported lazily inside the functions below — the
# adapters package triggers @register_adapter discovery on first import,
# and the new adapters that use this module create a circular import.

_log = setup_logger(__name__)


@dataclass(frozen=True, slots=True)
class ClickCapture:
    """Result of a successful click_and_capture run.

    The caller forwards ``cookies`` + ``user_agent`` on the actual file
    GET so the signed URL is honoured by the source server.
    """

    download_url: str
    suggested_filename: str
    cookies: dict[str, str]
    user_agent: str


def click_and_capture(
    url: str,
    *,
    button_text: str | None = None,
    button_selector: str | None = None,
    wait_for_url_pattern: str | None = None,
    timeout: int = 30,
    pre_click_sleep: float = 1.5,
) -> ClickCapture:
    """Sync entry point — runs the async cycle in the vendored CDP worker.

    Adapters call this via ``await asyncio.to_thread(click_and_capture, …)``
    so the cdp_driver event loop (in its own worker thread, see
    ``_CDP_WORKER`` inside the vendored ``internal_bypasser``) does not
    contend with FastAPI's loop.
    """
    from grabarr.adapters.base import AdapterBypassError

    if not button_text and not button_selector:
        raise ValueError("click_and_capture: provide button_text or button_selector")
    try:
        from grabarr.vendor.shelfmark.bypass import internal_bypasser
    except ImportError as exc:
        raise AdapterBypassError(
            "click_and_capture requires the 'internal-bypasser' extra: "
            "`uv sync --extra internal-bypasser`"
        ) from exc

    return internal_bypasser._CDP_WORKER.run(
        _click_and_capture_async(
            url,
            button_text=button_text,
            button_selector=button_selector,
            wait_for_url_pattern=wait_for_url_pattern,
            timeout=timeout,
            pre_click_sleep=pre_click_sleep,
        ),
        timeout=timeout + 60,
    )


async def _click_and_capture_async(
    url: str,
    *,
    button_text: str | None,
    button_selector: str | None,
    wait_for_url_pattern: str | None,
    timeout: int,
    pre_click_sleep: float,
) -> ClickCapture:
    """The actual driver — boots Chromium, clicks, captures, returns."""
    from grabarr.adapters.base import AdapterBypassError
    from grabarr.vendor.shelfmark.bypass import internal_bypasser
    import mycdp.browser as cdp_browser

    driver: Any = None
    try:
        driver = await internal_bypasser._create_cdp_browser(url)
        page = driver.main_tab

        # The DownloadWillBegin CDP event fires BEFORE the bytes start
        # streaming, so we capture the URL the browser is about to GET
        # without needing to abort the download. Chromium will write a
        # partial file to its scratch dir; the surrounding _close_cdp_driver
        # in `finally` releases it. set_download_behavior("deny") would be
        # cleaner but the API surface differs across cdp_driver versions
        # and a failed call short-circuits the rest of this function.

        loop = asyncio.get_running_loop()
        captured: asyncio.Future[tuple[str, str]] = loop.create_future()
        url_filter = re.compile(wait_for_url_pattern) if wait_for_url_pattern else None

        def _on_download(event: cdp_browser.DownloadWillBegin) -> None:
            if captured.done():
                return
            if url_filter and not url_filter.search(event.url):
                _log.debug(
                    "click_driver: skipping non-matching URL %s", event.url
                )
                return
            _log.info(
                "click_driver: captured download → %s (suggested=%s)",
                event.url, event.suggested_filename,
            )
            captured.set_result((event.url, event.suggested_filename))

        page.add_handler(cdp_browser.DownloadWillBegin, _on_download)

        # Give lazy JS time to attach handlers + finish countdowns.
        await asyncio.sleep(pre_click_sleep)

        # Click. CSS selector takes priority; fall back to text match.
        clicked = False
        if button_selector:
            try:
                await page.click(button_selector)
                clicked = True
            except Exception as exc:  # noqa: BLE001
                _log.info(
                    "click_driver: selector %r failed: %s", button_selector, exc
                )
        if not clicked and button_text:
            elem = await page.find(button_text, best_match=True, timeout=10)
            if elem is None:
                raise AdapterBypassError(
                    f"click_driver: no element matching {button_text!r} on {url}"
                )
            await elem.click()

        try:
            file_url, suggested_name = await asyncio.wait_for(
                captured, timeout=timeout
            )
        except TimeoutError as exc:
            raise AdapterBypassError(
                f"click_driver: no download event within {timeout}s for {url} "
                "(button may not have triggered a download, or "
                "wait_for_url_pattern filtered out the URL)"
            ) from exc

        # Snapshot the cookies + UA for the caller to forward.
        cookies: dict[str, str] = {}
        try:
            cookies_list = await driver.cookies.get_all()
            cookies = {c.name: c.value for c in cookies_list}
        except Exception as exc:  # noqa: BLE001
            _log.debug("click_driver: cookies fetch failed: %s", exc)
        ua = ""
        try:
            ua = await page.evaluate("navigator.userAgent") or ""
        except Exception as exc:  # noqa: BLE001
            _log.debug("click_driver: UA fetch failed: %s", exc)

        return ClickCapture(
            download_url=file_url,
            suggested_filename=suggested_name,
            cookies=cookies,
            user_agent=ua,
        )
    finally:
        if driver is not None:
            try:
                from grabarr.vendor.shelfmark.bypass.internal_bypasser import (
                    _close_cdp_driver,
                )

                await _close_cdp_driver(driver)
            except Exception as exc:  # noqa: BLE001
                _log.debug("click_driver: driver close failed: %s", exc)
